package jsbuild

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/evanw/esbuild/pkg/api"
)

// RegistryModule is the virtual module that resolves to the generated
// island registry; the runtime entry imports it as
// `import { registry } from "airway-islands-registry"`.
const RegistryModule = "airway-islands-registry"

// islandsPlugin generates the island registry on the fly: every build —
// including dev rebuilds — rescans the islands directory, so adding an
// island file requires no manual registration. Each island file must
// default-export its component; its registry name is the file path relative
// to islands/ without the extension.
func islandsPlugin(islandsDir string) api.Plugin {
	return api.Plugin{
		Name: "airway-islands",
		Setup: func(build api.PluginBuild) {
			build.OnResolve(api.OnResolveOptions{Filter: "^" + RegistryModule + "$"},
				func(args api.OnResolveArgs) (api.OnResolveResult, error) {
					return api.OnResolveResult{Path: RegistryModule, Namespace: "airway-islands"}, nil
				})
			build.OnLoad(api.OnLoadOptions{Filter: ".*", Namespace: "airway-islands"},
				func(args api.OnLoadArgs) (api.OnLoadResult, error) {
					code, err := generateRegistry(islandsDir)
					if err != nil {
						return api.OnLoadResult{}, err
					}
					// the generated module's relative imports resolve from the
					// source root (e.g. "./islands/counter.tsx")
					return api.OnLoadResult{
						Contents:   &code,
						Loader:     api.LoaderTS,
						ResolveDir: filepath.Dir(islandsDir),
					}, nil
				})
		},
	}
}

func generateRegistry(islandsDir string) (string, error) {
	islands, err := collectIslands(islandsDir)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("// Code generated by airway js:build — do not edit.\n")
	b.WriteString("// One entry per file under islands/; default-export the component.\n")
	if len(islands) == 0 {
		b.WriteString("export const registry: Record<string, (props: any) => any> = {};\n")
		return b.String(), nil
	}

	for i, name := range islands {
		fmt.Fprintf(&b, "import Island%d from \"./islands/%s\";\n", i, name)
	}
	b.WriteString("\nexport const registry: Record<string, (props: any) => any> = {\n")
	for i, name := range islands {
		fmt.Fprintf(&b, "  \"%s\": Island%d,\n", name, i)
	}
	b.WriteString("};\n")
	return b.String(), nil
}

// collectIslands lists island names (paths under dir without extension,
// slash-separated). Files and directories prefixed with "_" are treated as
// partials and skipped. A missing directory yields an empty list.
func collectIslands(dir string) ([]string, error) {
	var names []string
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			if os.IsNotExist(err) {
				return nil
			}
			return err
		}
		if d.IsDir() {
			if path != dir && strings.HasPrefix(d.Name(), "_") {
				return filepath.SkipDir
			}
			return nil
		}
		if strings.HasPrefix(d.Name(), "_") {
			return nil
		}
		ext := filepath.Ext(d.Name())
		if ext != ".tsx" && ext != ".ts" {
			return nil
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		names = append(names, strings.TrimSuffix(filepath.ToSlash(rel), ext))
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(names)
	return names, nil
}
