// Package jspkg manages frontend npm dependencies without a Node toolchain.
// It talks to an npm-compatible registry over HTTP, resolves every package
// (including transitive dependencies) to an exact version, and unpacks the
// tarballs into a vendor directory laid out like node_modules so esbuild can
// resolve imports through its NodePaths option.
package jspkg

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

const (
	// ManifestFile is the project-level dependency manifest. `deps` holds the
	// direct dependencies as exact versions (user intent, hand-editable);
	// `lock` is the fully resolved tree — transitive dependencies included —
	// regenerated by Add/Install and consumed by Install for reproducible
	// offline installs.
	ManifestFile = "js.pkg.json"

	// VendorDir is where package tarballs are unpacked, relative to the
	// project root. The layout mirrors node_modules (each package keeps its
	// own package.json) so esbuild resolves exports/main correctly.
	VendorDir = "app/assets/js/vendor"

	// DefaultRegistry is used when AIRWAY_JS_REGISTRY is not configured.
	DefaultRegistry = "https://registry.npmjs.org"
)

// Manifest is the on-disk representation of js.pkg.json.
type Manifest struct {
	Deps map[string]string    `json:"deps"`
	Lock map[string]LockedPkg `json:"lock"`
}

// LockedPkg pins one package of the resolved tree.
type LockedPkg struct {
	Version   string `json:"version"`
	Integrity string `json:"integrity,omitempty"`
}

// ReadManifest loads js.pkg.json from root; a missing file yields an empty
// manifest instead of an error, so `airway js:add` works in a fresh project.
func ReadManifest(root string) (*Manifest, error) {
	data, err := os.ReadFile(filepath.Join(root, ManifestFile))
	if err != nil {
		if os.IsNotExist(err) {
			return &Manifest{
				Deps: map[string]string{},
				Lock: map[string]LockedPkg{},
			}, nil
		}
		return nil, err
	}

	var m Manifest
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parse %s: %w", ManifestFile, err)
	}
	if m.Deps == nil {
		m.Deps = map[string]string{}
	}
	if m.Lock == nil {
		m.Lock = map[string]LockedPkg{}
	}
	return &m, nil
}

// WriteManifest writes js.pkg.json back to root, sorted for stable diffs.
func WriteManifest(root string, m *Manifest) error {
	data, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return os.WriteFile(filepath.Join(root, ManifestFile), data, 0o644)
}
