package openapi

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/gin-gonic/gin"
)

// BuildOptions tune Build for the caller: the CLI passes the project's
// version and a local server URL, the HTTP endpoint derives the server URL
// from the request.
type BuildOptions struct {
	// Server fills servers[0].url; omitted when empty.
	Server string
	// Title is the fallback for Document.Title ("Airway API").
	Title string
	// Version is the fallback for Document.Version ("dev").
	Version string
	// Warn reports declarations that match no registered route; nil silences.
	Warn func(format string, args ...any)
}

// specVersion is the emitted OpenAPI version. The document stays inside the
// 3.1/3.2 common subset (no 3.2-only keywords) so client generators with
// 3.1-level parsers consume it as well.
const specVersion = "3.2.0"

// BuiltInfo is the document root (info/servers only, for tests).
type BuiltInfo struct {
	Title       string `json:"title"`
	Summary     string `json:"summary,omitempty"`
	Description string `json:"description,omitempty"`
	Version     string `json:"version"`
}

type serverObject struct {
	URL string `json:"url"`
}

type componentsObject struct {
	Schemas         map[string]*Schema        `json:"schemas,omitempty"`
	SecuritySchemes map[string]SecurityScheme `json:"securitySchemes,omitempty"`
}

type specDocument struct {
	OpenAPI    string                           `json:"openapi"`
	Info       BuiltInfo                        `json:"info"`
	Servers    []serverObject                   `json:"servers,omitempty"`
	Tags       []TagDecl                        `json:"tags,omitempty"`
	Paths      map[string]map[string]*Operation `json:"paths"`
	Security   *[]map[string][]string           `json:"security,omitempty"`
	Components *componentsObject                `json:"components,omitempty"`
}

// Build enumerates the engine's routes and merges the declared operations
// into a deterministic OpenAPI document, pretty-printed with a trailing
// newline. Routes without a declaration are documented with the framework's
// default JSON envelope.
func Build(r *gin.Engine, opts BuildOptions) ([]byte, error) {
	registerComponent("Error", &Schema{
		Types: TypeList{"object"},
		Properties: map[string]*Schema{
			"code":    Int(),
			"data":    Any(),
			"message": Str(),
		},
		Required: []string{"code", "message"},
	})

	declMu.Lock()
	doc := docDecl
	declaredOps := make(map[string]*Operation, len(declared))
	for key, op := range declared {
		declaredOps[key] = op
	}
	declMu.Unlock()

	if doc == nil {
		doc = &Document{}
	}

	components := snapshotComponents()
	paths := map[string]map[string]*Operation{}

	for _, route := range r.Routes() {
		path := normalizePath(route.Path)
		if excludedPath(path, doc.exclusions) {
			continue
		}

		// OpenAPI path items key operations by lowercase method.
		method := strings.ToLower(route.Method)
		item := paths[path]
		if item == nil {
			item = map[string]*Operation{}
			paths[path] = item
		}
		if _, dup := item[method]; dup {
			continue
		}

		item[method] = defaultOperation(route.Method, path, route.Handler)
	}

	for key, decl := range declaredOps {
		method, path, _ := strings.Cut(key, " ")
		if excludedPath(path, doc.exclusions) {
			continue
		}

		item, ok := paths[path]
		if !ok || item[strings.ToLower(method)] == nil {
			if opts.Warn != nil {
				opts.Warn("openapi: declared %s %s matches no registered route", method, path)
			}
			continue
		}

		mergeOperation(item[strings.ToLower(method)], decl)
	}

	assignOperationIDs(paths)
	tags := collectTags(doc, paths)

	out := specDocument{
		OpenAPI: specVersion,
		Info: BuiltInfo{
			Title:   firstNonEmpty(doc.title, opts.Title, "Airway API"),
			Summary: doc.summary,
			Description: firstNonEmpty(doc.description,
				"Generated by `airway openapi:generate`; enrich each module with an openapi.go declaration (see docs/openapi.md)."),
			Version: firstNonEmpty(doc.version, opts.Version, "dev"),
		},
		Tags:  tags,
		Paths: paths,
		Components: &componentsObject{
			Schemas:         components,
			SecuritySchemes: doc.security,
		},
	}

	if opts.Server != "" {
		out.Servers = []serverObject{{URL: opts.Server}}
	}

	// Without declared security schemes the API is explicitly public; an
	// empty root-level security requirement tells clients (and linters) so.
	if len(doc.security) == 0 {
		out.Security = &[]map[string][]string{}
	}

	body, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(body, '\n'), nil
}

// defaultOperation documents an undeclared route: handler-derived
// operationId, a tag from the first meaningful path segment, auto-detected
// path parameters and the default JSON envelope response.
func defaultOperation(method, path, handler string) *Operation {
	op := &Operation{
		method:      method,
		path:        path,
		operationID: handlerShortName(handler),
		tags:        []string{tagFromPath(path)},
		responses: map[string]*Response{
			"200": {content: map[string]Media{
				"application/json": {Schema: envelopeSchema(nil)},
			}},
		},
	}

	for _, name := range pathParams(path) {
		op.parameters = append(op.parameters, Parameter{
			Name: name, In: "path", Required: true, Schema: Str(),
		})
	}

	return op
}

// mergeOperation overlays a declaration onto an auto-documented operation:
// scalar fields override when set, declared parameters shadow the
// auto-detected ones with the same name, and explicit request bodies and
// responses replace the defaults.
func mergeOperation(op *Operation, decl *Operation) {
	if decl.operationID != "" {
		op.operationID = decl.operationID
	}
	if len(decl.tags) > 0 {
		op.tags = decl.tags
	}
	if decl.summary != "" {
		op.summary = decl.summary
	}
	if decl.description != "" {
		op.description = decl.description
	}
	if decl.deprecated {
		op.deprecated = true
	}
	if len(decl.security) > 0 {
		op.security = decl.security
	}

	if len(decl.parameters) > 0 {
		shadowed := map[string]bool{}
		for _, p := range decl.parameters {
			if p.In == "path" {
				shadowed[p.Name] = true
			}
		}

		kept := op.parameters[:0]
		for _, p := range op.parameters {
			if !shadowed[p.Name] {
				kept = append(kept, p)
			}
		}
		op.parameters = append(kept, decl.parameters...)
	}

	if decl.requestBody != nil {
		op.requestBody = decl.requestBody
	}
	if len(decl.responses) > 0 {
		op.responses = decl.responses
	}
}

// assignOperationIDs makes operationIds unique: identical handler names on
// several routes (or declarations) get a method suffix, then a counter.
func assignOperationIDs(paths map[string]map[string]*Operation) {
	used := map[string]int{}

	for _, path := range sortedPaths(paths) {
		for _, method := range sortedMethods(paths[path]) {
			op := paths[path][method]
			if op.operationID == "" {
				op.operationID = strings.ToLower(method) + strings.ReplaceAll(
					strings.Trim(path, "/"), "/", "-")
			}

			count := used[op.operationID]
			used[op.operationID] = count + 1
			if count > 0 {
				suffix := "_" + strings.ToLower(method)
				if used[op.operationID+suffix] > 0 {
					suffix = fmt.Sprintf("_%d", count+1)
				}
				op.operationID += suffix
				used[op.operationID] = 1
			}
		}
	}
}

// collectTags merges declared tag metadata with every tag referenced by an
// operation, sorted by name.
func collectTags(doc *Document, paths map[string]map[string]*Operation) []TagDecl {
	byName := map[string]string{}
	for _, tag := range doc.tags {
		byName[tag.Name] = tag.Description
	}

	for _, item := range paths {
		for _, op := range item {
			for _, name := range op.tags {
				if _, ok := byName[name]; !ok {
					byName[name] = ""
				}
			}
		}
	}

	names := make([]string, 0, len(byName))
	for name := range byName {
		names = append(names, name)
	}
	sort.Strings(names)

	tags := make([]TagDecl, 0, len(names))
	for _, name := range names {
		tags = append(tags, TagDecl{Name: name, Description: byName[name]})
	}
	return tags
}

// normalizePath rewrites gin ":name" and "*name" segments to OpenAPI
// "{name}" placeholders; already-normalized paths pass through unchanged.
func normalizePath(path string) string {
	segments := strings.Split(path, "/")
	for i, segment := range segments {
		if len(segment) > 1 && (segment[0] == ':' || segment[0] == '*') {
			segments[i] = "{" + segment[1:] + "}"
		}
	}
	return strings.Join(segments, "/")
}

// excludedPath reports whether path matches any exclusion pattern
// (exact match, or prefix match for patterns ending in "*").
func excludedPath(path string, patterns []string) bool {
	for _, pattern := range patterns {
		if pattern == path || normalizePath(pattern) == path {
			return true
		}
		if trimmed := strings.TrimSuffix(pattern, "*"); trimmed != pattern {
			if strings.HasPrefix(path, trimmed) {
				return true
			}
		}
	}
	return false
}

// pathParams extracts the "{name}" placeholders of a normalized path.
func pathParams(path string) []string {
	var names []string
	for _, segment := range strings.Split(path, "/") {
		if len(segment) > 2 && segment[0] == '{' && segment[len(segment)-1] == '}' {
			names = append(names, segment[1:len(segment)-1])
		}
	}
	return names
}

// handlerShortName reduces a fully-qualified handler name
// ("github.com/x/app/api/storage_api.UploadAction") to
// "storage_api.UploadAction".
func handlerShortName(handler string) string {
	if i := strings.LastIndexByte(handler, '/'); i >= 0 {
		handler = handler[i+1:]
	}
	return handler
}

// tagFromPath picks a default tag: the first segment outside the /api/v1
// prefix ("storage" for /api/v1/storage/*key).
func tagFromPath(path string) string {
	for _, segment := range strings.Split(path, "/") {
		if segment == "" || segment == "api" || segment == "v1" {
			continue
		}
		return segment
	}
	return "root"
}

func sortedPaths(paths map[string]map[string]*Operation) []string {
	out := make([]string, 0, len(paths))
	for path := range paths {
		out = append(out, path)
	}
	sort.Strings(out)
	return out
}

func sortedMethods(item map[string]*Operation) []string {
	out := make([]string, 0, len(item))
	for method := range item {
		out = append(out, method)
	}
	sort.Strings(out)
	return out
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if value != "" {
			return value
		}
	}
	return ""
}
