create table posts (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT REFERENCES users (id),
  title VARCHAR(255) UNIQUE NOT NULL,
  content TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
