create table media_files (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL references users(id),
  filename VARCHAR(255) UNIQUE NOT NULL,
  mime VARCHAR(255) NOT NULL,
  bytes BIGINT NOT NULL,
  expired_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
