FROM m.daocloud.io/docker.io/library/golang:1.27-alpine AS builder
WORKDIR /app
COPY . /app
RUN go build -o ./bin/app .

FROM m.daocloud.io/docker.io/library/alpine
WORKDIR /app
COPY --from=builder /app/bin/app /app
COPY --from=builder /app/db /app/db

ENV AIRWAY_ENV=production
ENV LISTEN=:1900
ENV TZ="Asia/Shanghai"

EXPOSE 1900

CMD ["/app/app"]
