FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY . /app
RUN go build -o ./bin/app .

FROM alpine
WORKDIR /app
COPY --from=builder /app/bin/app /app
COPY --from=builder /app/db /app/db

ENV AIRWAY_ENV=production
ENV PORT=1900
ENV TZ="Asia/Shanghai"

EXPOSE 1900

CMD ["/app/app"]
